version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    links: 
      - mysql
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes: 
      - .:/var/www/html
      - ./.docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./.docker/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./.docker/logs/access.log:/var/log/apache2/access.log
      - ./.docker/logs/error.log:/var/log/apache2/error.log
  
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./.docker/mysql:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_ARBITRARY: 1